Разметка мобильной версии
htmlacademy-adaptive/1439397-cat-energy-29 pull request #2
Opened 2023-07-28 14:04 UTC by AAV1ASOV

2023-07-28 16:12 UTC, Kartaviy-arteom requested changes

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/catalog.html
> +        </svg>
Тут будет что-то такое 
```
<picture>
              <source media="(min-width: 1200px)"
                srcset="../img/stack.svg#logo-desktop" width="202" height="59">
              <source media="(min-width: 768px)"
                srcset="../img/stack.svg#logo-tablet" width="174" height="52">
              <img class="logo__img" src="../img/stack.svg#logo-mobile"
                srcset="../img/stack.svg#logo-mobile" width="35" height="38" alt="Логотип - Кэт энерджи.">
            </picture>
```

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/catalog.html
> +      <ul class="catalog__list catalog-list">
на этой странице нужно продумать структуру разделов заголовков. Сейчас у тебя один h1 и 15 h2.
На странице мы можем выделить несколько основных разделов основные товары, дополнительные товары, блок с акцией и схему проезда. Внутри них могут быть еще заголовки.

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/catalog.html
> +          <a class="product-card__button card-button button" href="form.html">
лучше оставить `href="#"` всетаки там у тебя подбор программ, а не страница заказа

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/catalog.html
> +    <section class="show-more">
с этой карточкой тебе будет проще работать, если она будет у тебя с карточками товаров

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/catalog.html
> +      </a>
здесь не нужно два интерактивных элемента, тут это все об одном

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/catalog.html
> +    </section>
в акции можно тоже ссылку добавить

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/catalog.html
> +        <a class="copyright__logo-link" href="https://htmlacademy.ru/intensive/adaptive">
можно одной ссылкой

2023-07-28 16:12 UTC, Kartaviy-arteom commented on source/index.html
> +          </ul>
В данном случае можно просто сделать одну обертку с двумя картинками, но можно впринципе и списком

2023-08-09 06:49 UTC, AAV1ASOV commented on source/catalog.html
> +        </svg>
в мобильной версии рисунок логотипа и текст будут одной img или двумя? просто они в Фигме не сгруппированы в один блок, как для планшета и десктопа, поэтому и я разбил их на две штуки:
        <picture>
          <source media="(min-width: 1200px)" srcset="../img/stack.svg#logo-desktop" width="202" height="59">
          <source media="(min-width: 768px)" srcset="../img/stack.svg#logo-tablet" width="174" height="52">
          <img class="logo__img" src="../img/stack.svg#logo-mobile" srcset="../img/stack.svg#logo-mobile" width="33"
            height="38" alt="Логотип - Кэт энерджи.">
          <img class="logo__text" src="../img/stack.svg#logo-mobile" srcset="../img/stack.svg#logo-mobile" width="101"
            height="18" alt="Логотип - Кэт энерджи.">
        </picture>

2023-08-14 15:24 UTC, Kartaviy-arteom approved these changes

2023-08-14 15:24 UTC, merged